### ISSUE TITLE
Support for python 3.4 subprocess module

### ISSUE THREAD

**Issue by chrissawer** [MutopiaProject/mupub#1]
I am using mupub on a CentOS 7 machine which has Python 3.4 installed from EPEL. This is also the version of Python 3 which ships with Debian Jessie.

Unfortunately the subprocess module has changed between Python 3.4 and Python 3.5 and currently mupub relies on the Python 3.5 version.

Is it possible without too much work to replace the calls to subprocess.run in build.py and lily.py to remain compatible with Python 3.4? There is some guidance in the Python docs:

https://docs.python.org/3.5/library/subprocess.html#call-function-trio

**Comment by glenl** [comment]
I doubt this is much work at all. My strategy is to install 3.4 and force the virtual environment to that for development. I don't recall anything that depends on 3.5 features but I was unaware of this difference.

**Comment by glenl** [comment]
This was easy enough to fix and I've made a release [(v0.4.1)](https://github.com/MutopiaProject/mupub/releases/tag/v0.4.1) with the changes. I've not tested it on 3.4 so please re-open it if still broken and I'll be more diligent regarding my development environment.

**Comment by chrissawer** [comment]
Fix looks good, thanks for the quick response. I have successfully built a piece using mupub on the Mutopia build server including RDF generation.
I will continue to explore how it works over the next few days, and improve my understanding of the python code and tests. Then we can start deleting legacy code/scripts!
